# Site settings
title: Dean Kelley
email: dean.a.kelley@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A place for me to disply my work and whatever else I feel like sharing.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://deanak1987.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# GitHub Pages specific settings
repository: deanak1987/deanak1987.github.io
github_username: deanak1987
linkedin_username: dean-kelley-0a7616103

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Collections (optional)
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"
  - scope:
      path: ""
    values:
      layout: "default"

# Pagination (if using jekyll-paginate)
paginate: 5
paginate_path: "/page:num/"

# Social links
social:
  - platform: github
    user_url: "https://github.com/deanak1987"
    display_name: "GitHub"
  - platform: linkedin
    user_url: "https://linkedin.com/in/dean-kelley-0a7616103"
    display_name: "LinkedIn"